services:
  - type: web
    name: deepfake-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn deepfake_detector.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "your-render-url.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://image-deepfake.vercel.app,http://localhost:5173"